title: TNI Cybersec
logo: /assets/img/logo.png
description: CTF writeups collection by <a href="https://tni-cybersec.github.io/">@TNI-Cybersec</a>
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-remote-theme
  
header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

google_analytics: UA-NNNNNNNN-N
