title: TNI Cybersec
logo: /assets/img/logo.png
description: CTF writeups collection by <a href="https://github.com/TNI-Cybersec">TNI-Cybersec</a>
markdown: kramdown
remote_theme: BDHU/minimalist
color-scheme: dark
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-relative-links
  
# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/TNI-Cybersec
  - name: Facebook
    icon: <i class="fa-brands fa-facebook"></i>
    link: https://facebook.com/TNICybersec
  - name: Project Repository
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
    link: https://github.com/TNI-Cybersec/writeups
  - name: To main website
    icon: <i class="fas fa-external-link-alt"></i>
    link: https://tni-cybersec.github.io
