title: TNI Cybersec
logo: /assets/img/logo.png
email: pranisa@tni.ac.th
description: CTF writeups collection by <a href="https://tni-cybersec.github.io/">@TNI-Cybersec</a>
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/TNI-Cybersec
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://www.bodunhu.com/blog/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
